server:
  port: 8087
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ms_producto
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka
  instance:
    hostname: localhost
